server:
  port: 8084

classcenter:
  mysql:
    hostname: localhost
    port: 3308
    database: classcenter_notice
    username: root
    password: YOUR_PASSWORD

  redis:
    host: localhost
    port: 6379
    database: 1

